name: Build Artifacts
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write      
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          architecture: x64
          cache: maven
      - name: Build
        run: mvn --batch-mode --update-snapshots test
