name: Build Artifacts
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write      
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
          architecture: x64
          cache: maven
          server-id: philterd-repository-releases
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Build and Deploy
        run: mvn --batch-mode --update-snapshots test deploy
        env:
          MAVEN_USERNAME: ${{ secrets.PHILTERD_ARTIFACTS_USER }}
          MAVEN_PASSWORD: ${{ secrets.PHILTERD_ARTIFACTS_TOKEN }}
